//! Validation against the official sing-box configuration JSON Schema.
//!
//! The bundled schema is generated by sing-box 1.14.0-beta.2 with its default
//! build tags. Keeping it in the binary makes validation deterministic and
//! avoids a network request every time Turntable runs.

use std::fmt;
use std::sync::OnceLock;

use serde_json::Value;

/// sing-box release that generated the bundled schema.
pub const SCHEMA_VERSION: &str = "1.14.0-beta.2";

/// Canonical URI published by sing-box for its configuration schema.
pub const SCHEMA_URI: &str = "https://sing-box.sagernet.org/schema.json";

const SCHEMA_JSON: &str = include_str!("../../schema/sing-box-1.14.0-beta.2.json");

/// One immutable official schema bundled with Turntable.
pub struct SchemaBundle {
    release: &'static str,
    schema_uri: &'static str,
    schema_json: &'static str,
    schema: OnceLock<Value>,
    validator: OnceLock<jsonschema::Validator>,
}

impl SchemaBundle {
    const fn new(
        release: &'static str,
        schema_uri: &'static str,
        schema_json: &'static str,
    ) -> Self {
        Self {
            release,
            schema_uri,
            schema_json,
            schema: OnceLock::new(),
            validator: OnceLock::new(),
        }
    }

    /// Exact sing-box release that generated this schema.
    pub const fn release(&self) -> &'static str {
        self.release
    }

    /// Canonical schema URI embedded in generated documents.
    pub const fn schema_uri(&self) -> &'static str {
        self.schema_uri
    }

    /// Return the parsed official schema.
    pub fn schema(&self) -> &Value {
        self.schema.get_or_init(|| {
            serde_json::from_str(self.schema_json)
                .expect("a bundled sing-box JSON Schema must be valid JSON")
        })
    }

    fn validator(&self) -> &jsonschema::Validator {
        self.validator.get_or_init(|| {
            jsonschema::validator_for(self.schema())
                .expect("a bundled sing-box JSON Schema must compile")
        })
    }

    /// Validate a JSON value against this schema release.
    pub fn validate(&'static self, value: &Value) -> Result<(), SchemaValidationError> {
        let violations: Vec<SchemaViolation> = self
            .validator()
            .iter_errors(value)
            .map(|error| SchemaViolation {
                instance_path: error.instance_path().to_string(),
                schema_path: error.schema_path().to_string(),
                message: error.to_string(),
            })
            .collect();

        if violations.is_empty() {
            Ok(())
        } else {
            Err(SchemaValidationError {
                release: self.release,
                violations,
            })
        }
    }

    /// Evaluate a schema-valid value and return annotations produced by the
    /// matching branches.
    pub(crate) fn annotations(&self, value: &Value) -> Vec<SchemaAnnotation> {
        self.validator()
            .evaluate(value)
            .iter_annotations()
            .map(|annotation| SchemaAnnotation {
                instance_path: annotation.instance_location.as_str().to_string(),
                schema_path: annotation.schema_location.to_string(),
                value: annotation.annotations.value().clone(),
            })
            .collect()
    }
}

/// Official schema generated by sing-box 1.14.0-beta.2 with default build
/// tags.
pub static SING_BOX_1_14_0_BETA_2: SchemaBundle =
    SchemaBundle::new(SCHEMA_VERSION, SCHEMA_URI, SCHEMA_JSON);

struct SchemaRegistration {
    bundle: &'static SchemaBundle,
    aliases: &'static [&'static str],
}

static SCHEMA_REGISTRY: &[SchemaRegistration] = &[SchemaRegistration {
    bundle: &SING_BOX_1_14_0_BETA_2,
    aliases: &["1.14"],
}];

/// Resolve an exact release identifier or temporary compatibility alias.
pub fn for_target(target: &str) -> Option<&'static SchemaBundle> {
    let target = target.trim();
    SCHEMA_REGISTRY
        .iter()
        .find(|registration| {
            registration.bundle.release == target || registration.aliases.contains(&target)
        })
        .map(|registration| registration.bundle)
}

/// Return canonical release identifiers for every bundled schema.
pub fn supported_releases() -> impl Iterator<Item = &'static str> {
    SCHEMA_REGISTRY
        .iter()
        .map(|registration| registration.bundle.release)
}

/// Return whether a target is an alias rather than an exact release.
pub fn is_alias(target: &str) -> bool {
    let target = target.trim();
    SCHEMA_REGISTRY
        .iter()
        .any(|registration| registration.aliases.contains(&target))
}

/// Return the newest bundled schema.
pub const fn default_bundle() -> &'static SchemaBundle {
    &SING_BOX_1_14_0_BETA_2
}

/// One actionable JSON Schema violation.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SchemaViolation {
    /// JSON Pointer locating the invalid value.
    pub instance_path: String,
    /// JSON Pointer locating the violated schema keyword.
    pub schema_path: String,
    /// Human-readable validator message.
    pub message: String,
}

impl fmt::Display for SchemaViolation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let path = if self.instance_path.is_empty() {
            "/"
        } else {
            &self.instance_path
        };
        write!(f, "{path}: {}", self.message)
    }
}

/// All violations found while validating a configuration.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SchemaValidationError {
    release: &'static str,
    violations: Vec<SchemaViolation>,
}

impl SchemaValidationError {
    /// Exact sing-box release whose schema rejected the document.
    pub const fn release(&self) -> &'static str {
        self.release
    }

    /// Return every schema violation in stable validator order.
    pub fn violations(&self) -> &[SchemaViolation] {
        &self.violations
    }
}

impl fmt::Display for SchemaValidationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(
            f,
            "sing-box {} schema validation failed with {} error(s)",
            self.release,
            self.violations.len()
        )?;
        for violation in &self.violations {
            writeln!(f, "- {violation}")?;
        }
        Ok(())
    }
}

impl std::error::Error for SchemaValidationError {}

/// Return the parsed official schema bundled with Turntable.
pub fn official_schema() -> &'static Value {
    default_bundle().schema()
}

/// One annotation emitted while evaluating a schema-valid document.
///
/// This is crate-internal because it exposes the JSON Schema engine's raw
/// annotation model. The semantic validator consumes sing-box extensions such
/// as `x-tag-reference` from these values.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct SchemaAnnotation {
    /// JSON Pointer locating the annotated value.
    pub instance_path: String,
    /// JSON Pointer locating the schema annotation.
    pub schema_path: String,
    /// Annotation value, or a bundle of unknown keyword annotations.
    pub value: Value,
}

/// Validate a JSON value against the bundled official schema.
pub fn validate(value: &Value) -> Result<(), SchemaValidationError> {
    default_bundle().validate(value)
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn official_schema_metadata_matches_beta_2() {
        let schema = official_schema();
        assert_eq!(
            schema["$schema"],
            "https://json-schema.org/draft/2020-12/schema"
        );
        assert_eq!(schema["$id"], SCHEMA_URI);
    }

    #[test]
    fn registry_resolves_exact_release_and_compatibility_alias() {
        assert!(std::ptr::eq(
            for_target("1.14.0-beta.2").unwrap(),
            &SING_BOX_1_14_0_BETA_2
        ));
        assert!(std::ptr::eq(
            for_target("1.14").unwrap(),
            &SING_BOX_1_14_0_BETA_2
        ));
        assert!(is_alias("1.14"));
        assert!(!is_alias("1.14.0-beta.2"));
        assert!(for_target("1.14.0").is_none());
    }

    #[test]
    fn accepts_a_minimal_configuration() {
        validate(&json!({
            "$schema": SCHEMA_URI,
            "outbounds": [{"type": "direct", "tag": "direct"}]
        }))
        .unwrap();
    }

    #[test]
    fn reports_nested_unknown_fields_with_json_pointer_paths() {
        let error = validate(&json!({
            "outbounds": [{
                "type": "direct",
                "tag": "direct",
                "future_option": true
            }]
        }))
        .unwrap_err();

        assert!(
            error
                .violations()
                .iter()
                .any(|violation| violation.instance_path == "/outbounds/0")
        );
        assert!(error.to_string().contains("future_option"));
    }
}
